services:
  bbs:
    container_name: bbs
    hostname: prime8.dev
    image: moncheeta/bbs
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/prime8.dev/fullchain.pem:/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/prime8.dev/privkey.pem:/ssl/privkey.pem:ro
    restart: always
    stop_grace_period: 1m

  mail:
    container_name: mail
    hostname: mail.prime8.dev
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    env_file: mail.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - mail:/data/:/var/mail/
      - mail:/state/:/var/mail-state/
      - mail:/logs/:/var/log/mail/
      - mail:/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    restart: always
    stop_grace_period: 1m

  git:
    container_name: git
    hostname: git.prime8.dev
    image: bacnh85/gitolite-cgit
    env_file: git.env
    volumes:
      - git:/var/lib/git/
    ports:
      - "22:22"
      - "80:80"
      - "9418:9418"

volumes:
  mail:
  git:
