services:
  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    volumes:
      - ./jail:/etc/fail2ban/jail.local:ro
      - /var/log/mail/mail.log:/var/log/mail/mail.log:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    networks:
      - www
    restart: always

  updates:
    container_name: updates
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--interval"
      - "120"
      - "--rolling-restart"
      - "--cleanup"
    restart: always

  web:
    container_name: web
    image: moncheeta/website
    ports:
      - "80:80"
      - "443:443"
    networks:
      - www
    volumes:
      - ./caddy:/etc/caddy/Caddyfile:ro
      - ./web/data/:/data/caddy/
      - ./web/config/:/config/caddy/
    restart: always

  mail:
    container_name: mail
    image: ghcr.io/docker-mailserver/docker-mailserver
    hostname: mail.prime8.dev
    env_file: ./mail/env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    networks:
      - www
    volumes:
      - ./mail/data/:/var/mail/
      - ./mail/state/:/var/mail-state/
      - ./mail/logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - ./web/data/certificates/acme.zerossl.com-v2-dv90/mail.prime8.dev/:/etc/certificates/:ro
    depends_on:
      - web
    cap_add:
      - NET_ADMIN
    restart: always

  repos:
    container_name: repos
    image: elsdoerfer/gitolite
    env_file: ./git/env
    volumes:
      - ./git/repos/:/var/lib/git/repositories/
      - ./git/ssh/:/var/lib/git/.ssh/
    ports:
      - "22:22"

  gitweb:
    container_name: gitweb
    image: rockstorm/gitweb
    depends_on:
      - repos
    volumes:
      - ./git/repos/:/srv/git/:ro
    expose:
      - "80"
    networks:
      - www

  csc:
    container_name: csc
    image: moncheeta/csc
    environment:
      - DOMAIN=csc.prime8.dev
    env_file: ./csc/env
    volumes:
      - ./csc/auth.json:/app/google_auth.json:ro
    expose:
      - "80"
    networks:
      - www

networks:
  www:
