services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    volumes:
      - ./jail:/etc/fail2ban/jail.local
      - /var/log/mail/:/var/log/mail/:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    networks:
      - common
    restart: always

  updates:
    container_name: updates
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--interval"
      - "120"
      - "--rolling-restart"
      - "--cleanup"
    restart: always

  web:
    container_name: web
    image: moncheeta/website:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - common
    volumes:
      - ./caddy:/etc/caddy/Caddyfile
      - ./web/data/:/data/caddy/
      - ./web/config/:/config/caddy/
    restart: always

  mail:
    container_name: mail
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail.prime8.dev
    env_file: ./mail/env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    networks:
      - common
    volumes:
      - ./mail/data/:/var/mail/
      - ./mail/state/:/var/mail-state/
      - ./mail/logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - ./web/data/certificates/acme.zerossl.com-v2-dv90/mail.prime8.dev/:/etc/certificates/
    depends_on:
      - web
    cap_add:
      - NET_ADMIN
    restart: always

  git:
    container_name: git
    image: woahbase/alpine-cgit:latest
    expose:
      - "80"
    volumes:
      - ./git/:/srv/git
    networks:
      - common
    restart: always

networks:
  common:
