services:
  bbs:
    container_name: bbs
    image: moncheeta/bbs
    hostname: prime8.dev
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/prime8.dev/fullchain.pem:/ssl/fullchain.pem
      - /etc/letsencrypt/live/prime8.dev/privkey.pem:/ssl/privkey.pem
    restart: always
    stop_grace_period: 1m
  mail:
    container_name: mail
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail.prime8.dev
    env_file: mail.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - /var/mail/data/:/var/mail/
      - /var/mail/state/:/var/mail-state/
      - /var/mail/logs/:/var/log/mail/
      - /var/mail/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    restart: always
    stop_grace_period: 1m
